win_len: 50
batch_size: 32
epochs: 10
learning_rate: 0.001
hidden_size: 128
num_heads: 4
num_layers: 2
datasets: ['diginetica']
mask_prob: 0.15
device: 'cpu'
eval_metrics: ['MRR', 'HIT', 'NDCG']
k: 10
min_session_length: 3
min_item_support: 5
data_dir: 'data'
processed_dir: 'data/processed'
recbole_config:
  model: BERT4Rec
  USER_ID_FIELD: session_id
  ITEM_ID_FIELD: item_id
  TIME_FIELD: timestamp
  ITEM_SEQ_FIELD: item_id_seq
  ITEM_SEQ_LEN_FIELD: seq_len
  neg_sampling: null
  train_neg_sample_args: null
  epochs: 10
  train_batch_size: 32
  eval_batch_size: 32
  device: cpu
  metrics: ['MRR', 'NDCG', 'Hit']
  valid_metric: MRR@10
  MAX_ITEM_LIST_LENGTH: 50
  embedding_size: 128
  hidden_size: 128
  num_layers: 2
  dropout_prob: 0.3
  loss_type: CE