# configs/cosmetics.yaml
dataset: cosmetics
win_len: 30
paths:
  raw: data_raw/cosmetics
  work: data_work/cosmetics
  proc: data_proc/cosmetics
train: {epochs: 10, batch_size: 128, lr: 1e-3, weight_decay: 1e-4}
model: {d: 128, heads: 2}
eval: {ks: [5,10,20]}
