dataset: cosmetics
paths: {proc: data_processed/cosmetics}
win_len: 30
model: {d: 192, heads: 4, pattern_M: 128}
train:
  batch_size: 256
  epochs: 40
  patience: 7
  lr: 0.0007
  weight_decay: 0.01
  num_neg: 800
