dataset: diginetica
paths: {proc: data_processed/diginetica}
win_len: 25
model: {d: 192, heads: 4, pattern_M: 128}
train:
  batch_size: 256
  epochs: 50
  patience: 7
  lr: 0.001
  weight_decay: 0.01
  num_neg: 600
