# configs/tmall.yaml
dataset: tmall
win_len: 70
paths:
  raw: data_raw/tmall
  work: data_work/tmall
  proc: data_proc/tmall
train:
  epochs: 10
  batch_size: 128
  lr: 1e-3
  weight_decay: 1e-4
model:
  d: 128
  heads: 2
eval:
  ks: [5, 10, 20]
