dataset: yoochoose
paths: {proc: data_processed/yoochoose}
win_len: 20
model: {d: 128, heads: 4, pattern_M: 128}
train:
  batch_size: 256
  epochs: 40
  patience: 6
  lr: 0.001
  weight_decay: 0.01
  num_neg: 600
